### ISSUE TITLE
Html-minifier on platformio

### ISSUE THREAD

**Issue by pbreizh29** [rene-d/wifinfo#22]
Very nice project, i would like to use it but i'm not able to use htm-minifier.
Is not installed, could you explain in the documentation how to install it.
For information i'm working on windows with platformiio

Thanks

**Comment by rene-d** [comment]
Thanks / merci / trugarez ;-). Je passe en français vu que ce projet ne peut intéresser que les français.

Je suppose qu'il faut installer NodeJS puis taper dans une console:
```bash
npm install html-minifier -g
```

C'est lors de l'appel du script `prep_data_folder.py` qu'on invoque html-minifier ainsi que gzip. Ce n'est pas une obligation, mais ça permet de le faire automatiquement.

Je conçois que ça ne soit pas simple avec Windows sans la palanquée d'outils en ligne de commande Linux/macOS.
