### ISSUE TITLE
Pas d'info de téléinformation.

### ISSUE THREAD

**Issue by coxifred** [rene-d/wifinfo#23]
Hello,
Super boulot !
Petite question, j'étais en version 1.5 de teleinfo. Mes données de téléinfo n'apparaissaient qu'en cliquant sur l'onglet configuration et recliquer sur teleinformation.
J'ai donc tenté la mise à jour avec ton projet. Mais du coup, je n'ai plus de téléinfo. Avant downgrading.. une idée ? 

Le /json est vide, donc je pense qu'il ne reçoit/décode pas.
C'est un esp8266.
Merci

**Comment by rene-d** [comment]
bonsoir, je suppose que tu parles du projet de CH Hallard. mon projet n'est pas compatible directement, "comme ça". je ne sais même plus trop les différences entre les 2... 
donc sauf à mettre les mains dans le cambouis, le mieux est de retourner vers la version originale que tu utilisais.

**Comment by coxifred** [comment]
> 
Merci d'avoir répondu. J'ai tenté un Tasmota, pareil, en fouinant un peu, et en changeant la lecture du RX de GPIO3 à GPIO13, cela fonctionne.
Surement lié à la variable SERIAL_7E1 initialisée sur le GPIO3 (Main.cpp). Je reste sur tasmota, le look web m'important peu.

Merci
